import { store, addEmployee } from "../store/employee-store.js";

export const mockDataGenerator = () => {
  const array = [
    "bir",
    "iki",
    "uc",
    "dort",
    "bes",
    "alti",
    "yedi",
    "sekiz",
    "dokuz",
    "on",
    "onbir",
    "oniki",
    "onuc",
    "ondort",
    "onbes",
    "onalti",
    "onyedi",
    "onsekiz",
    "ondokuz",
    "yirmi",
    "yirmibir",
    "yirmibiki",
    "yirmiuc",
    "yirmidort",
    "yirmibes",
    "yirmialti",
    "yirmiyedi",
    "yirmisekiz",
    "yirmidokuz",
    "otuz",
    "otuzbir",
    "otuziki",
    "otuzuc",
    "otuzdort",
    "otuzbes",
    "otuzalti",
    "otuzyedi",
    "otuzsekiz",
    "otuzdokuz",
    "kirk",
    "kirkbir",
    "kirkiki",
    "kirkuc",
    "kirkdort",
    "kirkbes",
    "kirkalti",
    "kirkyedi",
    "kirksekiz",
    "kirkdokuz",
    "elli",
    "elli bir",
    "elli iki",
    "elli uc",
    "elli dort",
    "elli bes",
    "elli alti",
    "elli yedi",
    "elli sekiz",
    "elli dokuz",
    "altmis",
    "altmis bir",
    "altmis iki",
    "altmis uc",
    "altmis dort",
    "altmis bes",
    "altmis alti",
    "altmis yedi",
    "altmis sekiz",
    "altmis dokuz",
    "yetmis",
    "yetmis bir",
    "yetmis iki",
    "yetmis uc",
    "yetmis dort",
    "yetmis bes",
    "yetmis alti",
    "yetmis yedi",
    "yetmis sekiz",
    "yetmis dokuz",
    "seksen",
    "seksen bir",
    "seksen iki",
    "seksen uc",
    "seksen dort",
    "seksen bes",
    "seksen alti",
    "seksen yedi",
    "seksen sekiz",
    "seksen dokuz",
    "doksan",
    "doksan bir",
    "doksan iki",
    "doksan uc",
    "doksan dort",
    "doksan bes",
    "doksan alti",
    "doksan yedi",
    "doksan sekiz",
    "doksan dokuz",
    "yuz",
    "yuz bir",
    "yuz iki",
    "yuz uc",
    "yuz dort",
    "yuz bes",
    "yuz alti",
    "yuz yedi",
    "yuz sekiz",
    "yuz dokuz",
    "yuz on",
    "yuz onbir",
    "yuz oniki",
    "yuz onuc",
    "yuz ondort",
    "yuz onbes",
    "yuz onalti",
    "yuz onyedi",
    "yuz onsekiz",
    "yuz ondokuz",
  ];
  array.map((item) => {
    store.dispatch(
      addEmployee({
        id: "emp_" + Date.now() + "_" + Math.floor(Math.random() * 1000000),
        firstName: item,
        lastName: "Working",
        email: "test@working.com",
        dateOfEmployment: "2024-01-01",
        dateOfBirth: "1990-01-01",
        phone: "901231231231",
        department: "Tech",
        position: "Junior",
      })
    );
  });
};
